
const LOAD_USER_ACTION = 'LOAD_USER_ACTION';
const PING = 'PING';
const PONG = 'PONG'
const UPDATE_USER_STATE_ACTION = 'UPDATE_USER_STATE_ACTION';


export {PING, PONG, LOAD_USER_ACTION, UPDATE_USER_STATE_ACTION};